[[redirects]]
  from = "http://sanimart.org"
  to = "https://www.sanimart.org/:splat"
  status = 302
  force = true

[[redirects]]
  from = "www.sanimart.org/*"
  to = "https://www.sanimart.org/:splat"
  status = 302
  force = true

[[redirects]]
  from = "sanimart.org"
  to = "https://www.sanimart.org/:splat"
  status = 302
  force = true